name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Define what repo the gh-pages branch should be deployed to.
      # - name: Add Remote Repo
      #   run: |
      #    git remote remove origin
      #    git remote add origin ${{ secrets.PAGES_REPO_NWO }}
      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.3.1
        env:
          PAGES_REPO_NWO: EnigmaEngine/EnigmaEngine.github.io # Override the repo that Jekyll points to.
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          provider: 'github'
          branch: 'gh-pages'         # Default is gh-pages for github provider